spring:
  data:
    mongodb:
      database: budgetcreator
server:
  port: 8000
logging:
  level:
    root: INFO
json-web-token:
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
    expiration: 28800
---
spring:
  config:
    activate:
      on-profile: logger
logging:
  level:
    root: INFO
