spring:
  data:
    mongodb:
      database: budgetcreator
server:
  port: 8000
logging:
  level:
    root: DEBUG
springbootwebfluxjjwt:
  password:
    encoder:
      secret: mysecret
      iteration: 33
      keylength: 256
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
    expiration: 28800
