spring:
#  profiles:
#    active: logger,return-errors
  datasource:
    url: jdbc:postgresql://localhost:5432/budget-creator?user=postgres&password=Truckin09
    driverClassName: org.postgresql.Driver
  exposed:
    generate-ddl: true
server:
  port: 8000
logging:
  level:
    root: INFO
json-web-token:
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
    expiration: 28800
---
spring:
  config:
    activate:
      on-profile: logger
logging:
  level:
    root: INFO
